name: Clojure CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Release
      run: lein release
    - name: Check
      run: ls resources/public
    - name: Vercel Deployment
      uses: xmflsct/action-vercel-deployment@v0.5.3
      with:
        vercelToken: ${{ secrets.VERCEL_TOKEN }}
        vercelOrgId: ${{ secrets.VERCEL_ORG_ID }}
        vercelProjectId: ${{ secrets.VERCEL_PROJECT_ID }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        deploySource: "resources/public"
      #   assignDomain: "preview.example.com"
      # env:
      #   YOUR_ENV_1: ${{ secrets.YOUR_ENV_1 }}
      #   YOUR_ENV_2: ${{ secrets.YOUR_ENV_2 }}